"""empty message

Revision ID: 785e33757ddd
Revises: ed6dfc7bb6e1
Create Date: 2018-03-22 04:06:19.699776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785e33757ddd'
down_revision = 'ed6dfc7bb6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('user_profile', sa.Column('datecreated', sa.DateTime(), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profile', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('photo_name', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_password_key', 'user_profile', type_='unique')
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['email'])
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.create_unique_constraint(u'user_profile_password_key', 'user_profile', ['password'])
    op.drop_column('user_profile', 'photo_name')
    op.drop_column('user_profile', 'location')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'datecreated')
    op.drop_column('user_profile', 'biography')
    # ### end Alembic commands ###
